services:
  # Dịch vụ Backend FastAPI
  api:
    build: ./backend
    container_name: api
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/src/app
    ports:
      - 8000:8000
    networks:
      - wallet_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

networks:
  wallet_network:
    name: network-bridge
    driver: bridge
